### ISSUE TITLE
Nejde přeložit

### ISSUE THREAD

**Issue by DenisHromada** [pepega007xd/SmrckaBat#1]
Na unixu `make` selže kvůli diakritice 😭

**Comment by pepega007xd** [comment]
It works on my pc

**Comment by pepega007xd** [comment]
Ale kdyby náhodou, tak `iconv -t ASCII//TRANSLIT SmrckaBat.c  -o SmrckaBat.c`

**Comment by DenisHromada** [comment]
> It works on my pc

Hádám, že ti to make buď automaticky překládá clangem, nebo máš novější verzi gcc než je na merlinovi. Tam totiž gcc diakritiku bohužel nepochroupá. Taky jí potom vadí bezejmenný parametr funkce `uno_reverse_card(int)`. 
Eva má naopak novější verzi gcc a překlad zvládá. Bezejmenný parametr pak novějšímu gcc vadí jen s flagem `-pedantic`.
